name: Send Secrets to VPS

on:
  workflow_dispatch:

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  DEPLOY_HOST: "sharednotes.app"
  DEPLOY_USER: "ubuntu"
  REPO_PATH: "/home/ubuntu/shared-notes"

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH with Passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH directory and permissions..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Adding deploy host to known_hosts..."
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Set up ssh-agent with a fixed socket path and add the key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to ensure configuration is correct..."
          ssh -v -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST "echo 'SSH connection successful'"

      - name: Send Secrets to VPS
        env:
          PROD_POSTGRES_CONNECTION_STRING: ${{ secrets.PROD_POSTGRES_CONNECTION_STRING }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "Sending secrets to the VPS securely..."
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST << EOF
            mkdir -p $REPO_PATH
            echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $REPO_PATH/secrets.env
            echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $REPO_PATH/secrets.env
            echo "PROD_POSTGRES_CONNECTION_STRING=$PROD_POSTGRES_CONNECTION_STRING" >> $REPO_PATH/secrets.env
            echo "SSH_PASSPHRASE=$SSH_PASSPHRASE" >> $REPO_PATH/secrets.env
            echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY" >> $REPO_PATH/secrets.env
            echo "VPS_HOST=$VPS_HOST" >> $REPO_PATH/secrets.env
            echo "VPS_USER=$VPS_USER" >> $REPO_PATH/secrets.env
            chmod 600 $REPO_PATH/secrets.env
          EOF
